server:
  port: 8080
  servlet:
    context-path: /cinema

spring:
  application:
    name: cinema
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: 123456
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      schema: public
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
        default_schema: public